version: 2.4

jobs:
  build:
    docker:
      - image: node:18.13.0
    working_directory: ~/mybrand/learn-express
    steps:
      - checkout:
            path: ~/mybrand
    - run: npm install
    - run: npm test

     