version: 2.4

jobs:
  build:
    docker:
      - image: node:18.13.0
    working_directory: ~/mybrand/learn-express
    steps:
      - checkout:
          path: ~/mybrand
      - run:
          name: Install dependencies
          command: npm install
          command: echo ${DB_URL}
      - run:
          name: Run tests
          command: npm test
